<?php
//display problem details
?>
<div class="detail_description">
      <?php
        echo '<h2>' . $this->proposal["nazov"] . '</h2>';
        echo '<p>' . $this->proposal["popis"] . '</p><br />';
        echo '<p><span>Autor: ' . $this->proposal["autor"] . '</span></p>';
  ?>
</div>
<h3>Problémy, ktoré rieši čiastočne</h3>
<div class="list-group">
  <?php
    foreach ($this->PPs as $PP) {
        echo '<a href="'  . $this->url(array('controller'=>'problem',
            'action'=>'detail', 'id'=>$PP['id']), null, true) . '" class="list-group-item">';
        echo '<h4 class="list-group-item-heading">' . $PP['name'] . '</h4>';
        echo '<p class="list-group-item-text">' . $PP['popis'] . '</p>';
        echo '</a>';
    }
    
    if (is_null($this->PPs) || empty($this->PPs)) {
        echo '<div class="alert alert-warning">Nebol nájdený žiaden výskyt</div>';
    }
  ?>
</div>
<h3>Problémy, ktoré rieši úplne</h3>
<div class="list-group">
  <?php
    foreach ($this->FPs as $FP) {
        echo '<a href="'  . $this->url(array('controller'=>'problem',
            'action'=>'detail', 'id'=>$FP['id']), null, true) . '" class="list-group-item">';
        echo '<h4 class="list-group-item-heading">' . $FP['name'] . '</h4>';
        echo '<p class="list-group-item-text">' . $FP['popis'] . '</p>';
        echo '</a>';
    }
    
    if (is_null($this->FPs) || empty($this->FPs)) {
        echo '<div class="alert alert-warning">Nebol nájdený žiaden výskyt</div>';
    }
  ?>
</div>
<?php
    echo $this->form ;
?>
