<p><a href="<?php echo $this->url(array('controller'=>'proposal',
        'action'=>'add'));?>">Pridat novy navrh</a></p>
<table class="table table-striped table-bordered table-hover table-condensed">
<tr>
    <th>Nazov</th>
    <th>&nbsp;</th>
</tr>
<?php foreach($this->proposals as $proposal) : ?>
<tr>
    <td><?php echo $this->escape($proposal->nazov);?></td>

    <td>
        <a href="<?php echo $this->url(array('controller'=>'proposal',
            'action'=>'edit', 'id'=>$proposal->id));?>">Upravit</a>
        <a href="<?php echo $this->url(array('controller'=>'proposal',
            'action'=>'delete', 'id'=>$proposal->id));?>">Vymazat</a>
    </td>
</tr>
<?php endforeach; ?>
</table>
