<h1>Návrhy riešení</h1>
<?php
    if (Zend_Registry::get('role') === 'manager') {
       
?>
<p><a href="<?php echo $this->url(array('controller'=>'proposal',
        'action'=>'add'));?>" class="print-none">Pridať</a></p>
<?php } ?>
<table class="table table-striped table-bordered table-hover table-condensed">
<?php foreach($this->proposals as $proposal) : ?>
<tr>
    <td class="list_item_name"><a class="detail_link" href="<?php echo $this->url(array('controller'=>'proposal',
        'action'=>'detail', 'id'=>$proposal->id));?>">
            <div style="height:100%;width:100%">
                <?php echo $this->escape($proposal->nazov);?>
            </div></a>
    </td>
    <?php
        if (Zend_Registry::get('role') === 'manager') {       
    ?>
    <td>
        <a href="<?php echo $this->url(array('controller'=>'proposal',
            'action'=>'delete', 'id'=>$proposal->id));?>" class="print-none">Vymazať</a>
    </td>
    <?php } ?>
</tr>
<?php endforeach; ?>
</table>
