<p><a href="<?php echo $this->url(array('controller'=>'proposal',
        'action'=>'add'));?>">Pridať</a></p>
<table class="table table-striped table-bordered table-hover table-condensed">
<tr>
    <th>Názov</th>
    <th>&nbsp;</th>
</tr>
<?php foreach($this->proposals as $proposal) : ?>
<tr>
    <td class="list_item_name"><a class="detail_link" href="<?php echo $this->url(array('controller'=>'proposal',
        'action'=>'detail', 'id'=>$proposal->id));?>">
            <div style="height:100%;width:100%">
                <?php echo $this->escape($proposal->nazov);?>
            </div></a>
    </td>

    <td>
        <a href="<?php echo $this->url(array('controller'=>'proposal',
            'action'=>'delete', 'id'=>$proposal->id));?>">Vymazať</a>
    </td>
</tr>
<?php endforeach; ?>
</table>
