<h1>Subjektívne problémy</h1>
<?php
    if (Zend_Registry::get('role') === 'manager') {
       
?>
<p><a href="<?php echo $this->url(array('controller'=>'problem',
        'action'=>'add','type'=>'sp'));?>" class="print-none">Pridať</a></p>
<?php } ?>
<table class="table table-striped table-bordered table-hover table-condensed">
<?php foreach($this->problems as $problem) { 
    if ($problem->subjektivny) { ?>
<tr>
    <td class="list_item_name"><a class="detail_link" href="<?php echo $this->url(array('controller'=>'problem',
        'action'=>'detail', 'id'=>$problem->id, 'type'=>'sp'));?>">
            <div style="height:100%;width:100%">
                <?php echo $this->escape($problem->nazov);?>
            </div></a>
    </td>
    <?php
        if (Zend_Registry::get('role') === 'manager') {       
    ?>
    <td>
        <a href="<?php echo $this->url(array('controller'=>'problem',
            'action'=>'delete', 'id'=>$problem->id));?> " class="print-none">Vymazať</a>
    </td>
    <?php } ?>
</tr>
    <?php }    
} ?>
</table>
<h1>Objektívne problémy</h1>
<?php
    if (Zend_Registry::get('role') === 'manager') {
       
?>
<p><a href="<?php echo $this->url(array('controller'=>'problem',
        'action'=>'add','type'=>'op'));?>" class="print-none">Pridať</a></p>
<?php } ?>
<table class="table table-striped table-bordered table-hover table-condensed">
<?php foreach($this->problems as $problem) { 
    if (!$problem->subjektivny) { ?>
<tr>
    <td class="list_item_name"><a class="detail_link" href="<?php echo $this->url(array('controller'=>'problem',
        'action'=>'detail', 'id'=>$problem->id, 'type'=>'op'));?>">
            <div style="height:100%;width:100%">
                <?php echo $this->escape($problem->nazov);?>
            </div></a>
    </td>
    <?php
        if (Zend_Registry::get('role') === 'manager') {       
    ?>
    <td>
        <a href="<?php echo $this->url(array('controller'=>'problem',
            'action'=>'delete', 'id'=>$problem->id));?>" class="print-none">Vymazať</a>
    </td>
    <?php } ?>
</tr>
    <?php }    
} ?>
</table>