<h1>Subjektívne problémy</h1>
<p><a href="<?php echo $this->url(array('controller'=>'problem',
        'action'=>'add','type'=>'sp'));?>">Nový subjektívny problém</a></p>
<table class="table table-striped table-bordered table-hover table-condensed">
<tr>
    <th>Názov</th>
    <th>&nbsp;</th>
</tr>
<?php foreach($this->problems as $problem) { 
    if ($problem->subjektivny) { ?>
<tr>
    <td><?php echo $this->escape($problem->nazov);?></td>

    <td>
        <a href="<?php echo $this->url(array('controller'=>'problem',
            'action'=>'edit', 'id'=>$problem->id, 'type'=>'sp'));?>">Upraviť</a>
        <a href="<?php echo $this->url(array('controller'=>'problem',
            'action'=>'delete', 'id'=>$problem->id));?>">Vymazať</a>
    </td>
</tr>
    <?php }    
} ?>
</table>
<h1>Objektívne problémy</h1>
<p><a href="<?php echo $this->url(array('controller'=>'problem',
        'action'=>'add','type'=>'op'));?>">Nový objektívny problém</a></p>
<table class="table table-striped table-bordered table-hover table-condensed">
<tr>
    <th>Názov</th>
    <th>&nbsp;</th>
</tr>
<?php foreach($this->problems as $problem) { 
    if (!$problem->subjektivny) { ?>
<tr>
    <td><?php echo $this->escape($problem->nazov);?></td>

    <td>
        <a href="<?php echo $this->url(array('controller'=>'problem',
            'action'=>'edit', 'id'=>$problem->id, 'type'=>'op'));?>">Upraviť</a>
        <a href="<?php echo $this->url(array('controller'=>'problem',
            'action'=>'delete', 'id'=>$problem->id));?>">Vymazať</a>
    </td>
</tr>
    <?php }    
} ?>
</table>