<p><a href="<?php echo $this->url(array('controller'=>'problem',
        'action'=>'add'));?>">Pridat novy problem</a></p>
<table class="table table-striped table-bordered table-hover table-condensed">
<tr>
    <th>Nazov</th>
    <th>&nbsp;</th>
</tr>
<?php foreach($this->problems as $problem) : ?>
<tr>
    <td><?php echo $this->escape($problem->nazov);?></td>

    <td>
        <a href="<?php echo $this->url(array('controller'=>'problem',
            'action'=>'edit', 'id'=>$problem->id));?>">Upravit</a>
        <a href="<?php echo $this->url(array('controller'=>'problem',
            'action'=>'delete', 'id'=>$problem->id));?>">Vymazat</a>
    </td>
</tr>
<?php endforeach; ?>
</table>
