<?php
//display problem details
?>
<div class="detail_description">
      <?php
        echo '<h2>' . $this->analysis["nazov"] . '</h2>';
        echo '<p>' . $this->analysis["popis"] . '</p><br />';
        echo '<p><span>Autor: ' . $this->analysis["autor"] . '</span></p>';
  ?>
</div>
<h3>Analyzované problémy</h3>
<div class="list-group">
  <?php
    foreach ($this->APs as $AP) {
        echo '<a href="'  . $this->url(array('controller'=>'problem',
            'action'=>'detail', 'id'=>$AP['id']), null, true) . '" class="list-group-item">';
        echo '<h4 class="list-group-item-heading">' . $AP['name'] . '</h4>';
        echo '<p class="list-group-item-text">' . $AP['popis'] . '</p>';
        echo '</a>';
    }
    
    if (is_null($this->APs) || empty($this->APs)) {
        echo '<div class="alert alert-warning">Nebol nájdený žiaden výskyt</div>';
    }
  ?>
</div>
<h3>Výstupné problémy</h3>
<div class="list-group">
  <?php
    foreach ($this->OPs as $OP) {
        echo '<a href="'  . $this->url(array('controller'=>'problem',
            'action'=>'detail', 'id'=>$OP['id']), null, true) . '" class="list-group-item">';
        echo '<h4 class="list-group-item-heading">' . $OP['name'] . '</h4>';
        echo '<p class="list-group-item-text">' . $OP['popis'] . '</p>';
        echo '</a>';
    }
    
    if (is_null($this->OPs) || empty($this->OPs)) {
        echo '<div class="alert alert-warning">Nebol nájdený žiaden výskyt</div>';
    }
  ?>
</div>
<?php
    echo $this->form ;
?>
