<?php
//display problem details
?>
<h2>Detailne informacie</h2>
<div class="panel panel-default">
    <div class="panel-heading">
        <?php echo $this->analysis["nazov"]; ?>
    </div>
    <div class="panel-body">
        <?php echo $this->analysis["popis"]; ?>
    </div>
    <div id="other" class="panel-footer">
        <dl class="dl-horizontal">
            <dt>Autor:</dt>
            <dd><?php echo $this->analysis["autor"]; ?></dd>
        </dl>
    </div>
</div>
<h2>Vstupne problemy</h2>
<div class="list-group">
  <?php
    foreach ($this->APs as $AP) {
        echo '<a href="#" class="list-group-item">';
        echo '<h4 class="list-group-item-heading">' . $AP['name'] . '</h4>';
        echo '<p class="list-group-item-text">' . $AP['popis'] . '</p>';
        echo '</a>';
    }
  ?>
</div>
<h2>Vystupne problemy</h2>
<div class="list-group">
  <?php
    foreach ($this->OPs as $OP) {
        echo '<a href="#" class="list-group-item">';
        echo '<h4 class="list-group-item-heading">' . $OP['name'] . '</h4>';
        echo '<p class="list-group-item-text">' . $OP['popis'] . '</p>';
        echo '</a>';
    }
  ?>
</div>
<?php
    echo $this->form ;
?>
