<h1>Analýzy</h1>
<?php
    if (Zend_Registry::get('role') === 'manager') {
       
?>
<p><a href="<?php echo $this->url(array('controller'=>'analysis',
        'action'=>'add'));?>" class="print-none">Pridať</a></p>
<?php } ?>
<table class="table table-striped table-bordered table-hover table-condensed">
<?php foreach($this->analyses as $analysis) : ?>
<tr>
    <td class="list_item_name"><a class="detail_link" href="<?php echo $this->url(array('controller'=>'analysis',
        'action'=>'detail', 'id'=>$analysis->id));?>">
            <div style="height:100%;width:100%">
                <?php echo $this->escape($analysis->nazov);?>
            </div></a>
    </td>
    <?php
        if (Zend_Registry::get('role') === 'manager') {       
    ?>
    <td>
        <a href="<?php echo $this->url(array('controller'=>'analysis',
            'action'=>'delete', 'id'=>$analysis->id));?>" class="print-none">Vymazať</a>
    </td>
    <?php } ?>
</tr>
<?php endforeach; ?>
</table>
