<p><a href="<?php echo $this->url(array('controller'=>'analysis',
        'action'=>'add'));?>">Nová analýza</a></p>
<table class="table table-striped table-bordered table-hover table-condensed">
<tr>
    <th>Názov</th>
    <th>&nbsp;</th>
</tr>
<?php foreach($this->analyses as $analysis) : ?>
<tr>
    <td><?php echo $this->escape($analysis->nazov);?></td>

    <td>
        <a href="<?php echo $this->url(array('controller'=>'analysis',
            'action'=>'edit', 'id'=>$analysis->id));?>">Upraviť</a>
        <a href="<?php echo $this->url(array('controller'=>'analysis',
            'action'=>'delete', 'id'=>$analysis->id));?>">Vymazať</a>
    </td>
</tr>
<?php endforeach; ?>
</table>
