<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Stratég');
echo $this->doctype(); ?>
<html>
<head>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headTitle(); ?>
    <?php echo $this->headStyle(); ?>
    <?php echo $this->headScript()->prependFile('https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js')
                                  ->appendFile('http://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/2.0.2/bootstrap.min.js'); ?>
    <?php echo $this->headLink()->prependStylesheet('//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css');  ?>
</head>
<body>
<div id="wrapper" class="container">
<?php
if (count($this->messages)) : ?>
<?php foreach ($this->messages as $message) : ?>
    <div class="alert alert-<?php echo $message->getType(); ?>"><?php echo $this->escape($message->getMessage()); ?></div>
<?php endforeach; ?>
<?php endif; ?>
<?php echo $this->layout()->content; ?>
</div>
</body>
</html>